// Global variables for dashboard state
let volumeData = null;
let sensitivityChart = null;
let scene, camera, renderer, controls, meshGroup;
let currentViewMode = 'mesh'; // mesh, wireframe, points
let autoRotate = true;

// Initialize Dashboard when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    fetchData();
});

// Fetch JSON data generated by python script
function fetchData() {
    fetch('output/volume_data.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            volumeData = data;
            populateDashboard(data);
            initChart(data);
            init3DViewer();
        })
        .catch(error => {
            console.error('Error fetching volume data:', error);
            document.getElementById('loading-text').innerText = 'Error loading volume_data.json. Make sure the python script ran successfully.';
        });
}

// Populate UI text, stats boxes, and tables
function populateDashboard(data) {
    // Volume panels
    document.getElementById('vol-nominal').innerText = `${data.nominal_volume_rounded.toLocaleString()} m³`;
    document.getElementById('vol-combined-rss').innerText = `${data.nominal_volume_rounded.toLocaleString()} ± ${data.combined_active_uncertainty.toLocaleString()} m³`;
    
    // Stats grid
    document.getElementById('stat-scale').innerText = data.final_scale.toFixed(4);
    document.getElementById('stat-cv').innerText = `${(data.scale_cv * 100).toFixed(1)}%`;
    document.getElementById('stat-rmse').innerText = data.subsets.find(s => s.keys.join(',') === data.optimal_keys.join(',')).rmse.toFixed(2);
    
    // Info grid
    document.getElementById('info-bbox-dims').innerText = `${data.bbox_dx.toFixed(2)}m x ${data.bbox_dy.toFixed(2)}m (${Math.round(data.bbox_area).toLocaleString()} m²)`;
    document.getElementById('info-active-area').innerText = `${Math.round(data.active_area).toLocaleString()} m²`;
    document.getElementById('info-max-height').innerText = `${data.max_height.toFixed(2)} m`;
    document.getElementById('info-avg-height').innerText = `${data.mean_height.toFixed(2)} m`;
    
    // Slider values
    document.getElementById('slide-vol').innerText = `${data.nominal_volume_rounded.toLocaleString()} m³`;
    document.getElementById('slide-height').innerText = `${data.implied_avg_height_active.toFixed(2)} m`;
    document.getElementById('slide-bbox-height').innerText = `${data.implied_avg_height_bbox.toFixed(2)} m`;

    // Populate Subsets Table
    const subsetsBody = document.querySelector('#subsets-table tbody');
    subsetsBody.innerHTML = '';
    data.subsets.forEach(subset => {
        const tr = document.createElement('tr');
        const subsetName = subset.keys.join(', ');
        const isOptimal = subset.keys.join(',') === data.optimal_keys.join(',');
        
        if (isOptimal) {
            tr.classList.add('selected-row');
        }
        
        tr.innerHTML = `
            <td>${subsetName} ${isOptimal ? '<span style="color: var(--accent-cyan); font-weight: bold;">[Opt]</span>' : ''}</td>
            <td>${subset.scale.toFixed(4)}</td>
            <td>${subset.rmse.toFixed(2)}</td>
            <td>${subset.max_err.toFixed(2)}</td>
            <td>${(subset.cv * 100).toFixed(1)}%</td>
        `;
        subsetsBody.appendChild(tr);
    });

    // Populate LOO Table
    const looBody = document.querySelector('#loo-table tbody');
    looBody.innerHTML = '';
    data.loo_validation.forEach(item => {
        const tr = document.createElement('tr');
        tr.innerHTML = `
            <td>Exclude ${item.excluded}</td>
            <td>${item.scale.toFixed(4)}</td>
            <td>${item.rmse.toFixed(2)}</td>
            <td>${item.max_err.toFixed(2)}</td>
            <td style="color: ${item.diff_pct > 5 ? 'var(--accent-red)' : 'var(--text-color)'}">${item.diff_pct.toFixed(2)}%</td>
        `;
        looBody.appendChild(tr);
    });

    // Populate Programmatic Validation list
    const validationList = document.getElementById('validation-list');
    validationList.innerHTML = '';
    
    // Scale check
    addValidationItem(validationList, 'Scale Factor in [18, 22] m/unit', 
        (data.final_scale >= 18 && data.final_scale <= 22), `${data.final_scale.toFixed(4)} m/unit`);
    
    // Volume check
    addValidationItem(validationList, 'Nominal Volume in [30k, 45k] m³', 
        (data.nominal_volume >= 30000 && data.nominal_volume <= 45000), `${Math.round(data.nominal_volume).toLocaleString()} m³`);
        
    // Outlier GCP4 check (GCP2 in sorted list)
    addValidationItem(validationList, 'Outlier GCP4 (triangulation noise) Rejected', 
        !data.optimal_keys.includes('GCP2'), 'Filtered Successfully');
        
    // Outlier GCP6 check (GCP1 in sorted list)
    addValidationItem(validationList, 'Outlier GCP6 (massive Z error) Rejected', 
        !data.optimal_keys.includes('GCP1'), 'Filtered Successfully');
        
    // RMSE minimum check
    const minRmse = Math.min(...data.subsets.map(s => s.rmse));
    const currentRmse = data.subsets.find(s => s.keys.join(',') === data.optimal_keys.join(',')).rmse;
    addValidationItem(validationList, 'Optimal Subset Minimizes Alignment RMSE', 
        (Math.abs(currentRmse - minRmse) < 1e-5), `RMSE = ${currentRmse.toFixed(2)} m`);
}

function addValidationItem(container, label, passed, detail) {
    const div = document.createElement('div');
    div.className = 'validation-item';
    div.innerHTML = `
        <span class="validation-label">${label} <span style="color: var(--text-muted); font-size: 11px; font-family: 'JetBrains Mono', monospace;">(${detail})</span></span>
        <span class="validation-badge ${passed ? 'badge-passed' : 'badge-failed'}">
            ${passed ? 'PASSED' : 'FAILED'}
        </span>
    `;
    container.appendChild(div);
}

// Chart.js initialization
function initChart(data) {
    const ctx = document.getElementById('chart-sensitivity').getContext('2d');
    
    // Generate labels: e.g. "-10 cm", "-5 cm", etc.
    const labels = data.offsets.map(o => `${(o * 100).toFixed(0)} cm`);
    
    // Colors
    const chartColor = '#06b6d4';
    const gridColor = 'rgba(255, 255, 255, 0.08)';
    
    sensitivityChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: 'Stockpile Volume (m³)',
                data: data.volumes_at_offsets,
                borderColor: chartColor,
                backgroundColor: 'rgba(6, 182, 212, 0.05)',
                borderWidth: 2,
                pointBackgroundColor: chartColor,
                pointBorderColor: '#0b0f19',
                pointBorderWidth: 2,
                pointRadius: 5,
                pointHoverRadius: 7,
                tension: 0.2,
                fill: true
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            return `Volume: ${Math.round(context.raw).toLocaleString()} m³`;
                        }
                    }
                }
            },
            scales: {
                x: {
                    grid: { color: gridColor },
                    ticks: { color: '#9ca3af', font: { family: 'JetBrains Mono', size: 10 } }
                },
                y: {
                    grid: { color: gridColor },
                    ticks: { color: '#9ca3af', font: { family: 'JetBrains Mono', size: 10 } }
                }
            }
        }
    });
}

// Handle Slider Input
function updateSensitivitySlider(value) {
    // Value represents plane shift index: -10, -5, 0, 5, 10
    const offsetVal = parseFloat(value) / 100.0;
    document.getElementById('slider-val').innerText = `${value > 0 ? '+' : ''}${value} cm`;
    
    // Find index in data offsets
    const idx = volumeData.offsets.findIndex(o => Math.abs(o - offsetVal) < 1e-4);
    if (idx !== -1) {
        const vol = volumeData.volumes_at_offsets[idx];
        const nominalVol = volumeData.nominal_volume;
        const pctChange = ((vol - nominalVol) / nominalVol) * 100;
        
        // Update texts
        document.getElementById('slide-vol').innerText = `${Math.round(vol).toLocaleString()} m³`;
        document.getElementById('slide-change').innerText = `${pctChange > 0 ? '+' : ''}${pctChange.toFixed(2)}%`;
        
        const impliedActiveHeight = vol / volumeData.active_area;
        const impliedBBoxHeight = vol / volumeData.bbox_area;
        document.getElementById('slide-height').innerText = `${impliedActiveHeight.toFixed(2)} m`;
        document.getElementById('slide-bbox-height').innerText = `${impliedBBoxHeight.toFixed(2)} m`;
        
        // Highlight active point on Chart.js
        sensitivityChart.setActiveElements([{
            datasetIndex: 0,
            index: idx
        }]);
        sensitivityChart.update();
        
        // Vertically translate Three.js model to visually represent plane shift!
        if (meshGroup) {
            // Shifting ground plane UP is visually equivalent to translating mesh DOWN
            // In Three.js, Y is height coordinate after mesh rotation
            meshGroup.position.y = -offsetVal;
        }
    }
}

// Tab Switching
function switchTab(tabId) {
    // Hide all tabs
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    
    // Show active tab
    document.getElementById(tabId).classList.add('active');
    
    // Highlight button
    event.currentTarget.classList.add('active');
}

// Color by height color mapping (Viridis style)
function getColorForHeight(h) {
    const color = new THREE.Color();
    if (h < 0.5) {
        // Interpolate between Purple (68, 1, 84) and Cyan (33, 145, 140)
        let t = h * 2;
        color.r = (1 - t) * 0.26 + t * 0.13;
        color.g = (1 - t) * 0.00 + t * 0.57;
        color.b = (1 - t) * 0.33 + t * 0.55;
    } else {
        // Interpolate between Cyan (33, 145, 140) and Yellow (253, 231, 37)
        let t = (h - 0.5) * 2;
        color.r = (1 - t) * 0.13 + t * 0.99;
        color.g = (1 - t) * 0.57 + t * 0.90;
        color.b = (1 - t) * 0.55 + t * 0.14;
    }
    return color;
}

// Three.js 3D Viewer initialization
function init3DViewer() {
    const container = document.querySelector('.viewer-container');
    const canvas = document.getElementById('canvas-3d');
    
    // Renderer
    renderer = new THREE.WebGLRenderer({ canvas: canvas, antialias: true });
    renderer.setSize(container.clientWidth, container.clientHeight);
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.shadowMap.enabled = true;

    // Scene
    scene = new THREE.Scene();
    scene.background = new THREE.Color('#040711');
    scene.fog = new THREE.FogExp2('#040711', 0.005);

    // Camera
    camera = new THREE.PerspectiveCamera(45, container.clientWidth / container.clientHeight, 0.1, 1000);
    camera.position.set(0, 150, 200);

    // Controls
    controls = new THREE.OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.05;
    controls.maxPolarAngle = Math.PI / 2 - 0.05; // Don't go below ground
    controls.autoRotate = autoRotate;
    controls.autoRotateSpeed = 1.0;

    // Lighting
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.4);
    scene.add(ambientLight);

    const dirLight1 = new THREE.DirectionalLight(0xffffff, 0.8);
    dirLight1.position.set(100, 200, 100);
    scene.add(dirLight1);

    const dirLight2 = new THREE.DirectionalLight(0x06b6d4, 0.3); // cyan ambient glow
    dirLight2.position.set(-100, -50, -100);
    scene.add(dirLight2);

    // Add Grid Base Helper (SVD Ground Plane representation)
    const gridHelper = new THREE.GridHelper(400, 50, '#111827', '#1e293b');
    gridHelper.position.y = 0.0;
    scene.add(gridHelper);

    // Load Mesh File
    const loader = new THREE.PLYLoader();
    document.getElementById('loading-text').innerText = 'Downloading 3D Mesh (mesh_calibrated.ply)...';
    
    loader.load('output/mesh_calibrated.ply', function(geometry) {
        document.getElementById('loading-text').innerText = 'Rendering Digital Twin...';
        
        // Calculate height map vertex colors
        const positions = geometry.attributes.position.array;
        
        // SVD Aligned mesh height coordinates are along the Z axis (positions[i*3 + 2])
        let minZ = Infinity;
        let maxZ = -Infinity;
        
        for (let i = 0; i < positions.length / 3; i++) {
            let z = positions[i * 3 + 2];
            if (z < minZ) minZ = z;
            if (z > maxZ) maxZ = z;
        }
        
        const colors = [];
        for (let i = 0; i < positions.length / 3; i++) {
            let z = positions[i * 3 + 2];
            let h = (z - minZ) / (maxZ - minZ || 1);
            let color = getColorForHeight(h);
            colors.push(color.r, color.g, color.b);
        }
        
        geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
        geometry.computeVertexNormals();
        
        // Materials
        const meshMat = new THREE.MeshStandardMaterial({
            vertexColors: true,
            roughness: 0.8,
            metalness: 0.1,
            side: THREE.DoubleSide
        });
        
        const wireframeMat = new THREE.MeshBasicMaterial({
            color: '#06b6d4',
            wireframe: true,
            transparent: true,
            opacity: 0.15
        });
        
        const pointsMat = new THREE.PointsMaterial({
            vertexColors: true,
            size: 0.5,
            transparent: true,
            opacity: 0.8
        });

        // Meshes
        const mesh = new THREE.Mesh(geometry, meshMat);
        const wireframe = new THREE.Mesh(geometry, wireframeMat);
        const points = new THREE.Points(geometry, pointsMat);
        
        meshGroup = new THREE.Group();
        meshGroup.add(mesh);
        meshGroup.add(wireframe);
        meshGroup.add(points);
        
        // Align model: PLY has height along Z, Three.js has height along Y
        // Rotate the mesh group so Z points UP (along Y axis in Three.js)
        meshGroup.rotation.x = -Math.PI / 2;
        
        // Center the geometry bounds
        geometry.computeBoundingBox();
        const center = new THREE.Vector3();
        geometry.boundingBox.getCenter(center);
        
        // Translate model to align center of ground XY plane with origin (0, 0)
        // Keep nominal ground height Z=0 aligned with Three.js Y=0
        mesh.position.set(-center.x, -center.y, 0);
        wireframe.position.set(-center.x, -center.y, 0);
        points.position.set(-center.x, -center.y, 0);
        
        scene.add(meshGroup);
        
        // Adjust camera to fit geometry
        reset3DCamera();
        
        // Hide loader
        document.getElementById('loading-overlay').style.opacity = '0';
        setTimeout(() => {
            document.getElementById('loading-overlay').style.display = 'none';
        }, 500);
        
        // Set Initial view mode
        setViewMode(currentViewMode);
        
    }, function(xhr) {
        if (xhr.total > 0) {
            const pct = Math.round((xhr.loaded / xhr.total) * 100);
            document.getElementById('loading-text').innerText = `Downloading mesh: ${pct}%`;
        }
    }, function(error) {
        console.error('An error happened loading the mesh:', error);
        document.getElementById('loading-text').innerText = 'Failed to load mesh_calibrated.ply. Viewing as point-cloud only.';
    });

    // Animation Loop
    function animate() {
        requestAnimationFrame(animate);
        controls.update();
        renderer.render(scene, camera);
    }
    animate();

    // Window Resize Handler
    window.addEventListener('resize', () => {
        camera.aspect = container.clientWidth / container.clientHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(container.clientWidth, container.clientHeight);
    });
}

// Switch between view modes
function setViewMode(mode) {
    currentViewMode = mode;
    
    // Highlight buttons
    document.getElementById('btn-mesh').classList.remove('active');
    document.getElementById('btn-wireframe').classList.remove('active');
    document.getElementById('btn-points').classList.remove('active');
    
    if (!meshGroup) return;
    
    const mesh = meshGroup.children[0];
    const wireframe = meshGroup.children[1];
    const points = meshGroup.children[2];
    
    if (mode === 'mesh') {
        mesh.visible = true;
        wireframe.visible = false;
        points.visible = false;
        document.getElementById('btn-mesh').classList.add('active');
    } else if (mode === 'wireframe') {
        mesh.visible = false;
        wireframe.visible = true;
        points.visible = false;
        document.getElementById('btn-wireframe').classList.add('active');
    } else if (mode === 'points') {
        mesh.visible = false;
        wireframe.visible = false;
        points.visible = true;
        document.getElementById('btn-points').classList.add('active');
    }
}

// Toggle Auto Rotate spin
function toggleAutoRotate() {
    autoRotate = !autoRotate;
    controls.autoRotate = autoRotate;
    document.getElementById('btn-auto-rotate').classList.toggle('active', autoRotate);
}

// Reset camera to default zoom angle
function reset3DCamera() {
    controls.reset();
    camera.position.set(0, 100, 160);
    controls.target.set(0, 10, 0);
}
